### ISSUE TITLE
Filter files while unpack

### ISSUE THREAD

**Issue by longtimeago** [maven-download-plugin/maven-download-plugin#43] opened 2015-09-01 19:43 UTC
It would be nice to have such feature, as sometimes we need to remove some files from distribution

**Comment by mykelalvis** [comment] 2017-03-01 01:23
This _sounds_ like a duplicate of #3

**Comment by mickaelistria** [comment] 2017-03-01 10:10
Indeed a dup of #3. Thanks for catching it @mykelalvis

**Closed by mickaelistria** 2017-03-01 10:10 UTC
